### PR TITLE
Add rdm_bw, rdm_latency benchmarks and --with-pmi configure option.

### PR DESCRIPTION
**Pull request by ztiffany**
Signed-off-by: Zach Tiffany ztiffany@cray.com

### CODE REVIEW

**Comment by ztiffany** [comment]
@hppritcha @sungeunchoi please review.

**Comment by hppritcha** [comment]
the fabtests doesn't build for mac with these changes.  looking at a fix.

**Comment by ztiffany** [comment]
Thanks.  I made the suggested fix myself and pushed a new version.

**Comment by sungeunchoi** [comment]
You're using an outdated version of Makefile.ac.  Maybe other files, but I that was the only one I noticed without doing an actual diff.

**Comment by sungeunchoi** [comment]
I'm trying to figure out the intent of the _common_ directory, so I can decide if moving these things into them is appropriate.  Moving libfabtests.la into it seems like something that should be done upstream.

**Comment by ztiffany** [comment]
libfabtests.la source was always in the /common.  I created a separate makefile for it to make sure it was built before my tests in /perf.  I could build my /perf tests in the top level makefile to avoid this.

**Comment by hppritcha** [comment]
Zach, let's just go ahead and merge what you have and I will switch to using PMI KVS.

**Comment by ztiffany** [comment]
I've updated my commit.  The subdir makefiles are gone.  ft_utils.c still relies on the Cray PMI allgather extension.

**Pull request merged**
