### PR TITLE
Add multi-domain unit test.

### LINKED ISSUE #9: unit/ep_test.c enhancement to create multiple ep's from one or more domains
It would be great to enhance the unit/ep_test.c to allow for more than one domain being instantiated, and more than one ep per domain to be opened.  This would test the gni provider's domain/ep open/close methods more than is done by the test currently.

### PR DESCRIPTION
**Pull request by ztiffany**
Signed-off-by: Zach Tiffany ztiffany@cray.com

@sungeunchoi @hppritcha Closes #9 .

### CODE REVIEW

**Comment by hppritcha** [comment]
add Fixes ofi-cray/fabtests-cray#9 to the commit message and github will close the issue when this PR is merged.

**Comment by hppritcha** [comment]
We've been including jumps to cleanup code in some of the other tests.  But maybe this is good enough Sung?

**Comment by sungeunchoi** [comment]
I think in general, it is encouraged to use `fi_allocinfo` and `fi_freeinfo` rather than building the structure yourself.  I suspect some of the older tests do this since these functions were only recently exported.  Note that I have found that having `NULL` fields for some of the structures versus having allocated but zeroed fields behaves differently for the sockets provider.  I noted this to Sean (and also that sending in a `NULL` hints behaved differently than sending in a zeroed hints structure).  I think he was going to check documentation, but I haven't followed up.

**Comment by hppritcha** [comment]
:+1:

**Comment by sungeunchoi** [comment]
ep_test.c needs a Cray copyright.

**Comment by ztiffany** [comment]
I added a Cray copyright to ep_test.c

**Comment by sungeunchoi** [comment]
:+1:

**Pull request merged**
